email: swapnillothe15@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Software engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sample
github_username:  swapnillothe
# Build settings
theme: minima
plugins:
  - jekyll-feed